import { type Exercise } from "./types";

/**
 * The static mat-Pilates library — 29 entries ported verbatim from
 * `spine-pilates-builder.html` (`LIB`). Field mapping: n→name, p→phase,
 * l→level, a→action, d→duration, c→cue, b→breath. Each entry gets a stable
 * kebab `key` used as the persisted `exerciseKey`.
 */
export const EXERCISES: readonly Exercise[] = [
  // Warm-Up
  {
    key: "breath-body-scan",
    name: "Breath & Body Scan",
    phase: "Warm-Up",
    level: "Beginner",
    action: "stability",
    duration: 180,
    cue: "Breathe into the back and sides of the ribcage — lateral thoracic breathing.",
    breath: "Slow, even breath",
  },
  {
    key: "pelvic-tilts",
    name: "Pelvic Tilts",
    phase: "Warm-Up",
    level: "Beginner",
    action: "stability",
    duration: 120,
    cue: "Draw the belly button gently toward the spine — a scoop, not a suck.",
    breath: "Exhale to tilt",
  },
  {
    key: "cat-cow",
    name: "Cat–Cow",
    phase: "Warm-Up",
    level: "Beginner",
    action: "extension",
    duration: 120,
    cue: "The spine is a string of pearls — articulate one pearl at a time.",
    breath: "Inhale arch · exhale round",
  },
  {
    key: "chest-lift",
    name: "Chest Lift",
    phase: "Warm-Up",
    level: "Beginner",
    action: "flexion",
    duration: 120,
    cue: "Knit the lower ribs toward each other; head heavy in the hands.",
    breath: "Exhale to lift",
  },
  // Core
  {
    key: "the-hundred",
    name: "The Hundred",
    phase: "Core",
    level: "Intermediate",
    action: "flexion",
    duration: 120,
    cue: "On the exhale, let the abdominals do the work — pump from the powerhouse.",
    breath: "5 in · 5 out",
  },
  {
    key: "single-leg-slide",
    name: "Single Leg Slide",
    phase: "Core",
    level: "Beginner",
    action: "stability",
    duration: 120,
    cue: "Keep the pelvis still as the leg slides — no rocking side to side.",
    breath: "Exhale to extend",
  },
  {
    key: "single-leg-stretch",
    name: "Single Leg Stretch",
    phase: "Core",
    level: "Intermediate",
    action: "flexion",
    duration: 120,
    cue: "Create opposition: reach the long leg as the abs scoop deeper.",
    breath: "Exhale each switch",
  },
  {
    key: "double-leg-stretch",
    name: "Double Leg Stretch",
    phase: "Core",
    level: "Intermediate",
    action: "flexion",
    duration: 120,
    cue: "Reach long, then circle the arms and hug the knees back to center.",
    breath: "Inhale reach · exhale hug",
  },
  {
    key: "criss-cross",
    name: "Criss-Cross",
    phase: "Core",
    level: "Intermediate",
    action: "rotation",
    duration: 120,
    cue: "Twist from the waist, not the elbow — reach armpit toward knee.",
    breath: "Exhale to rotate",
  },
  {
    key: "teaser",
    name: "Teaser",
    phase: "Core",
    level: "Advanced",
    action: "flexion",
    duration: 120,
    cue: "Roll up pearl by pearl; float the legs to meet the fingertips.",
    breath: "Exhale to rise",
  },
  // Spine
  {
    key: "roll-down",
    name: "Roll-Down",
    phase: "Spine",
    level: "Beginner",
    action: "flexion",
    duration: 120,
    cue: "Melt down one vertebra at a time, head heavy, knees soft.",
    breath: "Exhale to descend",
  },
  {
    key: "roll-up",
    name: "Roll-Up",
    phase: "Spine",
    level: "Intermediate",
    action: "flexion",
    duration: 120,
    cue: "Peel sequentially off the mat; don't hinge from the hips.",
    breath: "Exhale to peel up",
  },
  {
    key: "spine-stretch-forward",
    name: "Spine Stretch Forward",
    phase: "Spine",
    level: "Beginner",
    action: "flexion",
    duration: 120,
    cue: "Grow tall first, then curl forward over an imaginary beach ball.",
    breath: "Exhale to fold",
  },
  {
    key: "saw",
    name: "Saw",
    phase: "Spine",
    level: "Intermediate",
    action: "rotation",
    duration: 120,
    cue: "Twist from the waist and saw the pinky past the little toe.",
    breath: "Exhale to saw",
  },
  {
    key: "rolling-like-a-ball",
    name: "Rolling Like a Ball",
    phase: "Spine",
    level: "Intermediate",
    action: "flexion",
    duration: 120,
    cue: "Stay in the C-curve; control the roll — don't throw it.",
    breath: "Inhale back · exhale up",
  },
  // Hip & Leg
  {
    key: "pelvic-curl-bridge",
    name: "Pelvic Curl / Bridge",
    phase: "Hip & Leg",
    level: "Beginner",
    action: "extension",
    duration: 120,
    cue: "Roll up through the spine; ribs stay soft, no arching the back.",
    breath: "Exhale to lift",
  },
  {
    key: "leg-circles",
    name: "Leg Circles",
    phase: "Hip & Leg",
    level: "Intermediate",
    action: "stability",
    duration: 120,
    cue: "Anchor the pelvis; the leg draws circles from a still center.",
    breath: "Exhale across",
  },
  {
    key: "side-kick-series",
    name: "Side Kick Series",
    phase: "Hip & Leg",
    level: "Beginner",
    action: "stability",
    duration: 180,
    cue: "Lengthen both sides of the waist; the leg moves, the torso stays.",
    breath: "Exhale to kick",
  },
  {
    key: "clam",
    name: "Clam",
    phase: "Hip & Leg",
    level: "Beginner",
    action: "stability",
    duration: 120,
    cue: "Stack the hips; open the top knee without rolling back.",
    breath: "Exhale to open",
  },
  {
    key: "inner-thigh-lift",
    name: "Inner Thigh Lift",
    phase: "Hip & Leg",
    level: "Beginner",
    action: "stability",
    duration: 120,
    cue: "Lengthen the bottom leg long and lift from the inner thigh.",
    breath: "Exhale to lift",
  },
  // Extension
  {
    key: "dart",
    name: "Dart",
    phase: "Extension",
    level: "Beginner",
    action: "extension",
    duration: 120,
    cue: "Reach the fingertips toward the heels; lengthen the crown forward.",
    breath: "Exhale to lift",
  },
  {
    key: "swan-prep",
    name: "Swan Prep",
    phase: "Extension",
    level: "Beginner",
    action: "extension",
    duration: 120,
    cue: "Press the mat away; lift from the upper back, not the lower.",
    breath: "Inhale to rise",
  },
  {
    key: "swimming",
    name: "Swimming",
    phase: "Extension",
    level: "Intermediate",
    action: "extension",
    duration: 120,
    cue: "Opposite arm and leg reach long; keep the belly lifted off the mat.",
    breath: "Breathe in 5s",
  },
  {
    key: "single-leg-kick",
    name: "Single Leg Kick",
    phase: "Extension",
    level: "Intermediate",
    action: "extension",
    duration: 120,
    cue: "Keep the thighs lifted; pulse the heel toward the seat.",
    breath: "Exhale to pulse",
  },
  {
    key: "childs-pose",
    name: "Child's Pose",
    phase: "Extension",
    level: "Beginner",
    action: "stability",
    duration: 60,
    cue: "Let the back body breathe and release between extensions.",
    breath: "Long slow breath",
  },
  // Cool-Down
  {
    key: "supine-spinal-twist",
    name: "Supine Spinal Twist",
    phase: "Cool-Down",
    level: "Beginner",
    action: "rotation",
    duration: 120,
    cue: "Exhale and let the knees melt to one side, gaze opposite.",
    breath: "Exhale to release",
  },
  {
    key: "figure-four-stretch",
    name: "Figure-Four Stretch",
    phase: "Cool-Down",
    level: "Beginner",
    action: "stability",
    duration: 120,
    cue: "Cross and draw the thigh in; keep the sacrum heavy on the mat.",
    breath: "Breathe into the hip",
  },
  {
    key: "hamstring-stretch",
    name: "Hamstring Stretch",
    phase: "Cool-Down",
    level: "Beginner",
    action: "stability",
    duration: 120,
    cue: "Float the leg toward you; soften the opposite standing hip.",
    breath: "Exhale to deepen",
  },
  {
    key: "constructive-rest",
    name: "Constructive Rest",
    phase: "Cool-Down",
    level: "Beginner",
    action: "stability",
    duration: 180,
    cue: "Let the mat hold you; lengthen each exhale a little more.",
    breath: "Let breath settle",
  },
];

/** Lookup map by `key` for O(1) resolution from a saved `exerciseKey`. */
export const EXERCISE_BY_KEY: ReadonlyMap<string, Exercise> = new Map(
  EXERCISES.map((e) => [e.key, e]),
);

/** Resolve a library exercise from its key (undefined if not found). */
export function getExercise(key: string): Exercise | undefined {
  return EXERCISE_BY_KEY.get(key);
}
